### ISSUE TITLE
Book in ePub format?

### ISSUE THREAD

**Issue by georgyfarniev** [amejiarosario/dsa.js-data-structures-and-algorithms-in-javascript#19]
Hello, sorry if I’m asking in wrong place, but I was not able to find any contact form on your e-commerce site where you sell this book. 

I would like to purchase it, but I’m curious whether ePub format will be available soon? How long approximately it will take? And if I purchase it right now, will I get ePub update for free once it release?

Also, little suggestion, please create some contact form on your website or leave contacts so people can ask questions directly. 

Thanks for your great job.

**Comment by amejiarosario** [comment]
Yes, this is the right place to ask questions.

You are right, I'll add some way for people to ask me questions directly from the book website. Thanks for pointing that out.

About the ePub format, I'm going to focus on that this week. A couple of people have been asking for ePub and Mobi. My plan is to send an email with the new formats to everybody that purchased the book (no additional charge).

**Comment by georgyfarniev** [comment]
@amejiarosario thanks for answer. Gonna purchase it. Thank you.

**Comment by amejiarosario** [comment]
@georgyfarniev I sent an email with the book in new formats: ePub and Mobi. Let me know if that works ok for you.

**Comment by georgyfarniev** [comment]
@amejiarosario purchased just today, and received only PDF

**Comment by amejiarosario** [comment]
@georgyfarniev I haven't updated the system yet to automatically send all formats (currently working on this). I sent an email yesterday with the new formats to everybody that bought the book. I'll do the same for you.

**Comment by amejiarosario** [comment]
The system is updated now. Everybody from now on will receive all 3 formats PDF, ePub, Mobi

**Comment by georgyfarniev** [comment]
@amejiarosario still not yet received anything. Can you check please? Mail starts from **xmllink**

**Comment by georgyfarniev** [comment]
@amejiarosario received. Thank you.

**Comment by amejiarosario** [comment]
You are welcome
